// <auto-generated />
using System;
using CuaHangQuanAo.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CuaHangQuanAo.Infrastructure.Migrations
{
    [DbContext(typeof(CuaHangQuanAoDbContext))]
    partial class CuaHangQuanAoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.AnhSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<string>("TenAnhSP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamId");

                    b.ToTable("AnhSanPhams");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.ChiTietHoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int?>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<int?>("SanPhamBienTheId")
                        .HasColumnType("int");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int");

                    b.Property<string>("TenMau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("SanPhamBienTheId");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.GioHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SanPhamBienTheId")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamBienTheId");

                    b.HasIndex("UserId");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PhiVanChuyen")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDTNhanHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,0)");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("TrangThaiThanhToan")
                        .HasColumnType("tinyint");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.LoaiSP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLSP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoaiSPs");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.MauSac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LoaiId")
                        .HasColumnType("int");

                    b.Property<string>("MaMau")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiId");

                    b.ToTable("MauSacs");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.PhanQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuyen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhanQuyens");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(18,0)");

                    b.Property<byte?>("GioiTinh")
                        .HasColumnType("tinyint");

                    b.Property<string>("HuongDan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("KhuyenMai")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int?>("LoaiId")
                        .HasColumnType("int");

                    b.Property<int?>("LoaiSPId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThanhPhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThuongHieuId")
                        .HasColumnType("int");

                    b.Property<bool?>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.Property<string>("TrangThaiSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiSPId");

                    b.HasIndex("ThuongHieuId");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.SanPhamBienThe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MauId")
                        .HasColumnType("int");

                    b.Property<int?>("MauSacId")
                        .HasColumnType("int");

                    b.Property<int?>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int?>("SizeId")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MauSacId");

                    b.HasIndex("SanPhamId");

                    b.HasIndex("SizeId");

                    b.ToTable("SanPhamBienThes");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LoaiId")
                        .HasColumnType("int");

                    b.Property<string>("TenSize")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiId");

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.ThuongHieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenTH")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThuongHieus");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhanQuyenId")
                        .HasColumnType("int");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhanQuyenId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.AnhSanPham", b =>
                {
                    b.HasOne("CuaHangQuanAo.Domain.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.ChiTietHoaDon", b =>
                {
                    b.HasOne("CuaHangQuanAo.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CuaHangQuanAo.Domain.Entities.SanPhamBienThe", "SanPhamBienThe")
                        .WithMany()
                        .HasForeignKey("SanPhamBienTheId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamBienThe");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.GioHang", b =>
                {
                    b.HasOne("CuaHangQuanAo.Domain.Entities.SanPhamBienThe", "SanPhamBienThe")
                        .WithMany()
                        .HasForeignKey("SanPhamBienTheId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CuaHangQuanAo.Domain.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SanPhamBienThe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.HoaDon", b =>
                {
                    b.HasOne("CuaHangQuanAo.Domain.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.MauSac", b =>
                {
                    b.HasOne("CuaHangQuanAo.Domain.Entities.LoaiSP", "LoaiSP")
                        .WithMany()
                        .HasForeignKey("LoaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoaiSP");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.SanPham", b =>
                {
                    b.HasOne("CuaHangQuanAo.Domain.Entities.LoaiSP", "LoaiSP")
                        .WithMany()
                        .HasForeignKey("LoaiSPId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CuaHangQuanAo.Domain.Entities.ThuongHieu", "ThuongHieu")
                        .WithMany()
                        .HasForeignKey("ThuongHieuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoaiSP");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.SanPhamBienThe", b =>
                {
                    b.HasOne("CuaHangQuanAo.Domain.Entities.MauSac", "MauSac")
                        .WithMany()
                        .HasForeignKey("MauSacId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CuaHangQuanAo.Domain.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CuaHangQuanAo.Domain.Entities.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MauSac");

                    b.Navigation("SanPham");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.Size", b =>
                {
                    b.HasOne("CuaHangQuanAo.Domain.Entities.LoaiSP", "LoaiSP")
                        .WithMany()
                        .HasForeignKey("LoaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoaiSP");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.Users", b =>
                {
                    b.HasOne("CuaHangQuanAo.Domain.Entities.PhanQuyen", "PhanQuyen")
                        .WithMany()
                        .HasForeignKey("PhanQuyenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PhanQuyen");
                });

            modelBuilder.Entity("CuaHangQuanAo.Domain.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
